name: Terraform CI (fmt & validate)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Format check
        run: terraform fmt -check -recursive

      - name: Validate (no backend)
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform validate
